version: '3.11'
services:
  bot:
    image: app
    container_name: alumni_networking_bot
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GPT_API_KEY=${GPT_API_KEY}
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: bash -c "python app/telegram/api.py"

  db:
    image: postgres
    container_name: alumni_networking_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alumni_networking_bot
    volumes:
       - $HOME/docker/volumes/postgres2:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
